config/routes.rb
Rails.application.routes.draw do
  resources :expenditures

end

app/models/expenditure.rb
class Expenditure < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/expenditures_controller.rb
class ExpendituresController < ApplicationController
  before_action :set_expenditure, only: [:show, :edit, :update, :destroy]

  # GET /expenditures
  # GET /expenditures.json
  def index
    @expenditures = Expenditure.all
  end

  # GET /expenditures/1
  # GET /expenditures/1.json
  def show
  end

  # GET /expenditures/new
  def new
    @expenditure = Expenditure.new
  end

  # GET /expenditures/1/edit
  def edit
  end

  # POST /expenditures
  # POST /expenditures.json
  def create
    @expenditure = Expenditure.new(expenditure_params)

    respond_to do |format|
      if @expenditure.save
        format.html { redirect_to @expenditure, notice: 'Expenditure was successfully created.' }
        format.json { render :show, status: :created, location: @expenditure }
      else
        format.html { render :new }
        format.json { render json: @expenditure.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /expenditures/1
  # PATCH/PUT /expenditures/1.json
  def update
    respond_to do |format|
      if @expenditure.update(expenditure_params)
        format.html { redirect_to @expenditure, notice: 'Expenditure was successfully updated.' }
        format.json { render :show, status: :ok, location: @expenditure }
      else
        format.html { render :edit }
        format.json { render json: @expenditure.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /expenditures/1
  # DELETE /expenditures/1.json
  def destroy
    @expenditure.destroy
    respond_to do |format|
      format.html { redirect_to expenditures_url, notice: 'Expenditure was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_expenditure
      @expenditure = Expenditure.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def expenditure_params
      params.require(:expenditure).permit(:item, :cost, :date_of_purchase)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/expenditures_helper.rb
module ExpendituresHelper
end

app/views/expenditures/_form.html.erb
<%= form_for(@expenditure) do |f| %>
  <% if @expenditure.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@expenditure.errors.count, "error") %> prohibited this expenditure from being saved:</h2>

      <ul>
      <% @expenditure.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :item %><br>
    <%= f.text_field :item %>
  </div>
  <div class="field">
    <%= f.label :cost %><br>
    <%= f.text_field :cost %>
  </div>
  <div class="field">
    <%= f.label :date_of_purchase %><br>
    <%= f.text_field :date_of_purchase %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/expenditures/edit.html.erb
<h1>Editing expenditure</h1>

<%= render 'form' %>

<%= link_to 'Show', @expenditure %> |
<%= link_to 'Back', expenditures_path %>

app/views/expenditures/index.html.erb
<h1>Listing expenditures</h1>

<table>
  <thead>
    <tr>
      <th>Item</th>
      <th>Cost</th>
      <th>Date of purchase</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @expenditures.each do |expenditure| %>
      <tr>
        <td><%= expenditure.item %></td>
        <td><%= expenditure.cost %></td>
        <td><%= expenditure.date_of_purchase %></td>
        <td><%= link_to 'Show', expenditure %></td>
        <td><%= link_to 'Edit', edit_expenditure_path(expenditure) %></td>
        <td><%= link_to 'Destroy', expenditure, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Expenditure', new_expenditure_path %>

app/views/expenditures/new.html.erb
<h1>New expenditure</h1>

<%= render 'form' %>

<%= link_to 'Back', expenditures_path %>

app/views/expenditures/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Item:</strong>
  <%= @expenditure.item %>
</p>

<p>
  <strong>Cost:</strong>
  <%= @expenditure.cost %>
</p>

<p>
  <strong>Date of purchase:</strong>
  <%= @expenditure.date_of_purchase %>
</p>

<%= link_to 'Edit', edit_expenditure_path(@expenditure) %> |
<%= link_to 'Back', expenditures_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <h2>Does this show up?</h2>
  <link href="./assets/application.css" media="screen" rel="stylesheet" type="text/css">
  <script src=".assets/application.js" type="text/javascript"></script>
</head>
<body>
  <div id="main" class="container"></div>
</body>
</html>